version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: starter
    ports:
      - "3000:3000"
    env_file:                    
      - .env
    environment:
      - NEXT_PUBLIC_OPENAI_API_KEY=${NEXT_PUBLIC_OPENAI_API_KEY}
      - OPENAI_API_KEY=${NEXT_PUBLIC_OPENAI_API_KEY}  # ✅ Add this for server-side use

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"